EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'G_USUARIO'
      AND RDB$FIELD_NAME = 'SENHA_API'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE G_USUARIO ADD SENHA_API VARCHAR(260)';
END;

UPDATE G_USUARIO
SET SENHA_API = '$2b$12$3B5QmVN5YKhiPcMq49FwtO3khIEvh3TVsMsYdvsyOB9r0DogffooW'
WHERE SENHA_API IS NULL OR SENHA_API = '';

SET TERM ^ ;

EXECUTE BLOCK AS
  DECLARE VARIABLE char_len INTEGER;
BEGIN
  IF (EXISTS(
    SELECT 1
    FROM RDB$RELATION_FIELDS
    WHERE RDB$RELATION_NAME = 'T_SERVICO_ITEMPEDIDO'
      AND RDB$FIELD_NAME = 'TIPO_ITEM'
  )) THEN
  BEGIN
    SELECT COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH)
    FROM RDB$RELATION_FIELDS rf
    JOIN RDB$FIELDS f ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
    WHERE rf.RDB$RELATION_NAME = 'T_SERVICO_ITEMPEDIDO'
      AND rf.RDB$FIELD_NAME = 'TIPO_ITEM'
    INTO :char_len;

    IF (char_len IS NULL OR char_len <> 2) THEN
      EXECUTE STATEMENT 'ALTER TABLE T_SERVICO_ITEMPEDIDO ALTER COLUMN TIPO_ITEM TYPE VARCHAR(2)';
  END
END ^

SET TERM ; ^

INSERT INTO
    G_CONFIG_GRUPO (CONFIG_GRUPO_ID, DESCRICAO, SISTEMA_ID)
VALUES
    ((SELECT COALESCE(MAX(CONFIG_GRUPO_ID), 0) + 1 FROM G_CONFIG_GRUPO), 'SAAS', 2.00)
MATCHING (CONFIG_GRUPO_ID);

UPDATE OR INSERT INTO
    G_CONFIG (
        CONFIG_ID,
        CONFIG_GRUPO_ID,
        CONFIG_PADRAO_ID,
        SECAO,
        NOME,
        VALOR,
        DESCRICAO,
        TEXTO,
        TERMINAL,
        TIPO_VALOR,
        ATUALIZADO
    )
VALUES
    (
        (SELECT COALESCE(MAX(CONFIG_ID), 0) + 1 FROM G_CONFIG),
        (SELECT MAX(CONFIG_GRUPO_ID) FROM G_CONFIG_GRUPO),
        NULL,
        'PEDIDO',
        'RECIBO_MODELO_1',
        NULL,
        'Modelo do Recibo do Balcão',
        x'',
        NULL,
        '6',
        'S'
    )
MATCHING (CONFIG_ID);

UPDATE OR INSERT INTO
    G_CONFIG (
        CONFIG_ID,
        CONFIG_GRUPO_ID,
        CONFIG_PADRAO_ID,
        SECAO,
        NOME,
        VALOR,
        DESCRICAO,
        TEXTO,
        TERMINAL,
        TIPO_VALOR,
        ATUALIZADO
    )
VALUES
    (
        (SELECT COALESCE(MAX(CONFIG_ID), 0) + 1 FROM G_CONFIG),
        (SELECT MAX(CONFIG_GRUPO_ID) FROM G_CONFIG_GRUPO),
        NULL,
        'ATO',
        'MODELO_LIVRO',
        NULL,
        'Modelo Padrão de Livro',
        x'',
        NULL,
        '6',
        'S'
    )
MATCHING (CONFIG_ID);



ALTER TABLE T_LIVRO_NATUREZA ADD MODELO_LIVRO BLOB;
ALTER TABLE T_LIVRO_NATUREZA ADD MODELO_LIVRO_PDF BLOB;
ALTER TABLE T_LIVRO_NATUREZA ADD MODELO_TRASLADO BLOB;
ALTER TABLE T_LIVRO_NATUREZA ADD MODELO_TRASLADO_PDF BLOB;

ALTER TABLE G_MARCACAO_TIPO ALTER COLUMN NOME TYPE VARCHAR_120;

ALTER TABLE T_ATO ADD TEXTO_FINALIZACAO_TRASLADO BLOB;
ALTER TABLE T_ATO ADD TEXTO_ASSINATURA_TRASLADO BLOB;


INSERT INTO G_CONFIG (CONFIG_ID, CONFIG_GRUPO_ID, CONFIG_PADRAO_ID, SECAO, NOME, VALOR, DESCRICAO, TEXTO, TERMINAL, TIPO_VALOR, ATUALIZADO)
VALUES((SELECT COALESCE(MAX(CONFIG_ID), 0) + 1 FROM G_CONFIG), (SELECT MAX(CONFIG_GRUPO_ID) FROM G_CONFIG_GRUPO), 27, 'ATO', 'MODELO_ASSINATURA_NORMAL', NULL, 'Assinatura: Modelo assinatura normal', x'', NULL, '6', 'S');

INSERT INTO G_CONFIG (CONFIG_ID, CONFIG_GRUPO_ID, CONFIG_PADRAO_ID, SECAO, NOME, VALOR, DESCRICAO, TEXTO, TERMINAL, TIPO_VALOR, ATUALIZADO)
VALUES((SELECT COALESCE(MAX(CONFIG_ID), 0) + 1 FROM G_CONFIG), (SELECT MAX(CONFIG_GRUPO_ID) FROM G_CONFIG_GRUPO), 27, 'ATO', 'MODELO_ASSINATURA_PELA_DIGITAL', NULL, 'Assinatura: Modelo assinatura pela digital', x'', NULL, '6', 'S');

INSERT INTO G_CONFIG (CONFIG_ID, CONFIG_GRUPO_ID, CONFIG_PADRAO_ID, SECAO, NOME, VALOR, DESCRICAO, TEXTO, TERMINAL, TIPO_VALOR, ATUALIZADO)
VALUES((SELECT COALESCE(MAX(CONFIG_ID), 0) + 1 FROM G_CONFIG), (SELECT MAX(CONFIG_GRUPO_ID) FROM G_CONFIG_GRUPO), 27, 'ATO', 'MODELO_ASSINATURA_DIGITAL', NULL, 'Assinatura: Modelo assinatura digital', x'', NULL, '6', 'S');

ALTER TABLE T_ATO_VINCULOPARTE ADD TEXTO_QUALIFICACAO BLOB;

-- Adicionar o campo
ALTER TABLE T_SERVICO_PEDIDO
ADD PESSOA_ID_NFSE NUMERIC(10,2);

-- Criar índice para a FK
CREATE INDEX T_SERVICO_PEDIDO_T_PESSOA_NFSE_FK
ON T_SERVICO_PEDIDO (PESSOA_ID_NFSE);

-- Criar chave estrangeira
-- Criar chave estrangeira com outro nome exclusivo
ALTER TABLE T_SERVICO_PEDIDO
ADD CONSTRAINT FK_TSP_PESSOA_ID_NFSE
FOREIGN KEY (PESSOA_ID_NFSE)
REFERENCES T_PESSOA(PESSOA_ID);

ALTER TABLE T_HISTORICO ADD HASH VARCHAR(255);
ALTER TABLE T_HISTORICO ALTER COLUMN HASH POSITION 2;