import z from 'zod';

export const GUsuarioSchema = z.object({
  usuario_id: z.number().int().optional(),
  trocarsenha: z.string().optional(),
  login: z.string().optional(),
  senha: z.string().optional(),
  situacao: z.string().optional(),  
  nome_completo: z.string().min(1, 'O nome do usuário é obrigatório'),
  funcao: z.string().min(1, 'A função do usuário é obrigatória'),
  assina: z.string().optional(),
  sigla: z.string().optional(),
  usuario_tab: z.string().optional(),
  ultimo_login: z.string().optional(),
  ultimo_login_regs: z.string().optional(),
  data_expiracao: z.string().optional(),
  senha_anterior: z.string().optional(),
  andamento_padrao: z.string().optional(),
  lembrete_pergunta: z.string().optional(),
  lembrete_resposta: z.string().optional(),
  andamento_padrao2: z.string().optional(),
  receber_mensagem_arrolamento: z.string().optional(),  
  email: z.string().min(1, 'O e-mail do usuário é obrigatório'),
  assina_certidao: z.string().optional(),
  receber_email_penhora: z.string().optional(),
  foto: z.string().optional(),
  nao_receber_chat_todos: z.string().optional(),
  pode_alterar_caixa: z.string().optional(),
  receber_chat_certidao_online: z.string().optional(),
  receber_chat_cancelamento: z.string().optional(),
  cpf: z.string().min(1, 'O CPF do usuário é obrigatório'),
  somente_leitura: z.string().optional(),
  receber_chat_envio_onr: z.string().optional(),
  tipo_usuario: z.string().optional(),
  senha_api: z.string().optional(),
  confirma_senha_api: z.string().optional(),
});

export type GUsuarioFormValues = z.infer<typeof GUsuarioSchema>;